name: Full-Stack CI/CD

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install backend dependencies
        run: npm install
        working-directory: full-stack-test-task-back-end

      - name: Run backend tests
        run: npm run test:cov
        working-directory: full-stack-test-task-back-end

  frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install frontend dependencies
        run: npm install
        working-directory: Full-Stack-Test-Task-front-end

      - name: Start frontend
        run: npm run dev
        working-directory: Full-Stack-Test-Task-front-end

      - name: Run Cypress tests
        run: npx cypress run
        working-directory: Full-Stack-Test-Task-front-end
